version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: masterfansuser
      DB_PASS: masterfanspass
      DB_NAME: masterfansdb
      DB_PORT: 5432
      JWT_SECRET_KEY: "bXQ+QpRiJDI6LSZ+YsPzl8aZ2pZmr9L4hf8eXcRZ1sWx+7CpEmxl9RCC0b/Af6W+Rq9gXw=="
    depends_on:
      - db

  db:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: masterfansuser
      POSTGRES_PASSWORD: masterfanspass
      POSTGRES_DB: masterfansdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
